### ISSUE TITLE
Remove team fixture file data and redirect to original source data

### ISSUE THREAD

**Issue by leahriffell** [hopesgit/futbol#47]
**Why**:
We will reference original Team data as the dataset is manageable without pulling a sampling. 

**To-do:**
- Delete team fixture file from data directory 
- Update team_collection_test to direct to teams.csv instead of teams_fixture.csv
- Update stat_tracker_test to direct to teams.csv instead of teams_fixture.csv
- Update the assertion values in any tests that will now fail because they were calculated using the old dataset

**Comment by sarynm12** [comment]
Teams fixture file removed
-I corrected the teams collection count assertion from 20 to 32 to reflect count of all teams in the teams csv
-in teams collection class, as well as in stat tracker, the pathway has been redirected to teams.csv
