### ISSUE TITLE
Game Collection - Hardcoded file path

### ISSUE THREAD

**Issue by AngelaGuardia** [hopesgit/futbol#51]
The @game_path instance variable in the GameCollection class initialize method is being hardcoded to the fixture file. It should be just passed the game_path argument. I think this will fix our SpecHarness error as well.

```
  def initialize(game_path)
    @game_path = './data/games_fixture.csv' # <---- should be game_path
    @all_games = []
    create_games
  end
```

**Comment by sarynm12** [comment]
This is completely right, Angela! I just ran spec harness, and that fixes it. I can make a change in that game collection class and push directly up to main. Or I'll create a new PR!

**Comment by AngelaGuardia** [comment]
I'll just sneak it into my next PR if that's okay!
