### ISSUE TITLE
RSpec - numeric converter bug

### ISSUE THREAD

**Issue by AngelaGuardia** [hopesgit/futbol#59]
RSpec tests are failing because it expects numbers in the data to be strings not integers

**Comment by leahriffell** [comment]
@guardiac in looking at rspec failures it looks like we're running into this error for season_ids. Do you see this error for any other attributes that should also be a string?

**Comment by AngelaGuardia** [comment]
I think you got this in slack but anything that I think that it's any values that are and id that need to be strings!
