### ISSUE TITLE
GameTeam Seasonid Refactor

### ISSUE THREAD

**Issue by AngelaGuardia** [hopesgit/futbol#78]
I just realized that the game_id always starts with the start year of the season:

game_id: **2015**030142 , season_id: **2015**2016
game_id: **2016**030172, season_id: **2016**2017

This means we can generate the season_id attribute in the GameTeam data without having to pull in data from Game and thus fully eliminate nested iteration.

**Comment by leahriffell** [comment]
Ahhhh Nice find!!
