### ISSUE TITLE
rspec bug: expect attributes to be strings, not symbols 

### ISSUE THREAD

**Issue by leahriffell** [hopesgit/futbol#82]
Looks like we should not convert our attributes to symbols. We could probably just do this for our Team class, but it may be better for consistency to leave all class attributes as strings. 

`team_info` method error:

       `expected: {"abbreviation"=>"MIN", "franchise_id"=>"34", "link"=>"/api/v1/teams/18", "team_id"=>"18", "team_name"=>"Minnesota United FC"}
            got: {:abbreviation=>"MIN", :franchise_id=>"34", :id=>"18", :link=>"/api/v1/teams/18", :name=>"Minnesota United FC"}

       (compared using ==)

       Diff:
       @@ -1,6 +1,6 @@
       -"abbreviation" => "MIN",
       -"franchise_id" => "34",
       -"link" => "/api/v1/teams/18",
       -"team_id" => "18",
       -"team_name" => "Minnesota United FC",
       +:abbreviation => "MIN",
       +:franchise_id => "34",
       +:id => "18",
       +:link => "/api/v1/teams/18",
       +:name => "Minnesota United FC",`

**Comment by leahriffell** [comment]
@sarynm12 @hopesgit @guardiac I see a few ways to do this (ranked from most simple to least):

1. change hash keys to a string in `team_info` method 
2. import team attributes as a string instead of symbols 
3. import all class attributes as strings instead of symbols (not necessary to pass spec harness but could be better for consistency) 

Thoughts? I think the first option would be just fine but wanted to check with y'all before changing the way we import headers.

**Comment by AngelaGuardia** [comment]
I'm inclined to do the first option because I kinda disagree with the spec harness haha. It just makes so much sense to convert keys to symbols and numbers to integers and floats.

**Comment by sarynm12** [comment]
I was about to say the same. I think we go with the simplest way, and agree that the spec harness sucks

**Comment by leahriffell** [comment]
Haha I'm good with that since then we can keep using them as symbols elsewhere. I'll submit a PR now and if Hope has concerns we can discuss more. Thanks!
