### ISSUE TITLE
Update `rival` and `favorite_opponent` to calculate based on win % vs num of wins

### ISSUE THREAD

**Issue by leahriffell** [hopesgit/futbol#89]
Doesn't impact our tests right now using fixture data, but these methods are calculated using just the num of wins/losses to a team. According to spec, they should be the name of the opponent with the _highest or lowest win percentage_ against a specific team. 

**To fix:**
- Make sure opponents_and_num_result_for_team return a key/value pair even if the opponent has not won any games against a team (ex: "5" => 0)
- Divide opponents_and_num_result_for_team by the num of games they have played against each opponent
- Take the max and min for rival and favorite_opponent

**Comment by AngelaGuardia** [comment]
Good catch!!

**Comment by leahriffell** [comment]
I have these pretty much figured out but want to wait until all of Saryn's get merged to make a PR to avoid lots of merge conflicts!
